---
-  hosts: all
   become: true
   gather_facts: false
   tasks:

   - name: Update APT package manager repositories cache 
     apt:
      update_cache: yes
   - name: install java using ansible
     become: yes
     apt:
      name: "{{packages}}"
      state: present
     vars:
      packages:
        - openjdk-11-jdk

   - name: install python3-pip
     apt: 
       name: python3-pip

   - name: install python3 package
     apt: 
       name: python3 
